<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.1 (Python 3.9.2 on win32)" generated="20210408 22:18:01.988" rpa="false">
<suite id="s1" name="CheckOutFunction" source="D:\RobotFramework\Code\B2SDemo\Tests\CheckOutFunction.robot">
<test id="s1-t1" name="Verify check out with guest">
<kw name="Start Testcase" library="CommonFunctionality" type="setup">
<kw name="Open Browser">
<arguments>
<arg>${url}</arg>
<arg>chrome</arg>
</arguments>
<msg timestamp="20210408 22:18:02.327" level="FAIL">No keyword with name 'Open Browser' found.</msg>
<status status="FAIL" starttime="20210408 22:18:02.327" endtime="20210408 22:18:02.328"></status>
</kw>
<status status="FAIL" starttime="20210408 22:18:02.324" endtime="20210408 22:18:02.328"></status>
</kw>
<status status="FAIL" starttime="20210408 22:18:02.323" endtime="20210408 22:18:02.329" critical="yes">Setup failed:
No keyword with name 'Open Browser' found.</status>
</test>
<status status="FAIL" starttime="20210408 22:18:02.007" endtime="20210408 22:18:02.330"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="CheckOutFunction">CheckOutFunction</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210408 22:18:02.296" level="ERROR">Error in file 'D:\RobotFramework\Code\B2SDemo\Tests\CheckOutFunction.robot': Initializing test library 'Selenium2Library' with no arguments failed: TypeError: replace_string() got an unexpected keyword argument 'custom_unescaper'
Traceback (most recent call last):
  File "c:\Users\ADMIN\.vscode\extensions\jacobphilip.danfoss-robotframework-debug-1.4.3\out\RobotFrameworkDebugHelpers\robotf\running\testlibraries.py", line 167, in _get_instance
    return libcode(*self.positional_args, **dict(self.named_args))
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python39\site-packages\SeleniumLibrary\__init__.py", line 464, in __init__
    BrowserManagementKeywords(self),
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python39\site-packages\SeleniumLibrary\keywords\browsermanagement.py", line 37, in __init__
    self._webdriver_creator = WebDriverCreator(self.log_dir)
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python39\site-packages\SeleniumLibrary\base\librarycomponent.py", line 86, in log_dir
    logfile = BuiltIn().get_variable_value("${LOG FILE}")
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python39\site-packages\robot\libraries\BuiltIn.py", line 1443, in get_variable_value
    name = self._get_var_name(name)
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python39\site-packages\robot\libraries\BuiltIn.py", line 1716, in _get_var_name
    match.resolve_base(self._variables)
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python39\site-packages\robot\variables\search.py", line 88, in resolve_base
    self.base = variables.replace_string(</msg>
<msg timestamp="20210408 22:18:02.298" level="ERROR">Error in file 'D:\RobotFramework\Code\B2SDemo\Tests\CheckOutFunction.robot': Importing test library 'Library DebugLibrary' failed: ModuleNotFoundError: No module named 'Library DebugLibrary'
Traceback (most recent call last):
  File "c:\Users\ADMIN\.vscode\extensions\jacobphilip.danfoss-robotframework-debug-1.4.3\out\RobotFrameworkDebugHelpers\robotf\utils\importer.py", line 153, in _import
    return __import__(name, fromlist=fromlist)
PYTHONPATH:
  c:\Users\ADMIN\.vscode\extensions\jacobphilip.danfoss-robotframework-debug-1.4.3\out\RobotFrameworkDebugHelpers
  C:\Program Files\Python39\python39.zip
  C:\Program Files\Python39\DLLs
  C:\Program Files\Python39\lib
  C:\Program Files\Python39
  C:\Users\ADMIN\AppData\Roaming\Python\Python39\site-packages
  C:\Program Files\Python39\lib\site-packages</msg>
</errors>
</robot>
